fastlane_version '1.3.0'

default_platform :ios

platform :ios do

  lane :build do

    if ENV['BUILD_NUMBER']
      increment_build_number(build_number: ENV['BUILD_NUMBER'])
    end

    sigh(adhoc: true)

    profile_path = Fastlane::Actions.lane_context[Fastlane::Actions::SharedValues::SIGH_PROFILE_PATH]
    FileUtils.cd '../scripts'
    sh "PROVISIONING_PROFILE_FILE=#{profile_path} ./build.sh"
    FileUtils.cd '../fastlane'

  end

  lane :once do

    produce({
                produce_app_name: '<%= projectName %>',
                produce_language: 'English',
                produce_version: '1.0',
                produce_sku: '<%= projectName %>',
                produce_skip_itc: true
            })


    cert
    puts ENV['CER_FILE_PATH']

    FileUtils.cp ENV['CER_FILE_PATH'], '../scripts/certs/dist.cer'

    puts ENV['CER_CERTIFICATE_ID']

    FileUtils.cd '../scripts'
    sh './importPrivateKey.sh'
    FileUtils.cd '../fastlane'

  end

end
